name: 'Google Scholar Fetcher'
description: 'Fetch publications by Google Scholar ID.'
author: sxlllslgh

branding:
  icon: 'award'
  color: 'blue'

inputs:
  google-scholar-id:
    description: 'Google Scholar ID of researcher'
    required: true
  record-file:
    description: 'File to write the record'
    required: false
    default: ''
    
outputs:
  record:
    description: 'JSON record'
    
runs:
  using: 'node20'
  main: 'index.js'